# __First Jupyter Notebook__


In [57]:
import pandas as pd
from numpy.random import default_rng
import tempfile

In [7]:
df = pd.read_excel(r"\Users\justt\OneDrive\Desktop\ds book\Data-Science-Projects-with-Python-Second-Ed-main\Data-Science-Projects-with-Python-Second-Ed-main\Data\default_of_credit_card_clients__courseware_version_1_21_19.xls")

In [8]:
df.shape

(30000, 25)

In [9]:
df.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  

[5 rows x 25 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   ID                          30000 non-null  object
 1   LIMIT_BAL                   30000 non-null  int64 
 2   SEX                         30000 non-null  int64 
 3   EDUCATION                   30000 non-null  int64 
 4   MARRIAGE                    30000 non-null  int64 
 5   AGE                         30000 non-null  int64 
 6   PAY_1                       30000 non-null  object
 7   PAY_2                       30000 non-null  int64 
 8   PAY_3                       30000 non-null  int64 
 9   PAY_4                       30000 non-null  int64 
 10  PAY_5                       30000 non-null  int64 
 11  PAY_6                       30000 non-null  int64 
 12  BILL_AMT1                   30000 non-null  int64 
 13  BILL_AMT2                   30000 non-null  in

In [11]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [12]:
df['ID'].nunique()

29687

In [13]:
id_counts = df['ID'].value_counts()

In [14]:
id_counts.head()

dbf9fb14-2656    2
5f79f818-18af    2
297edb0f-3bb1    2
2a793ecf-05c6    2
6353fd55-d66e    2
Name: ID, dtype: int64

In [15]:
id_counts.value_counts()

1    29374
2      313
Name: ID, dtype: int64

In [16]:
rg = default_rng(12345)

In [17]:
random_integers = rg.integers(low=1, high=5, size=100)

In [18]:
random_integers[:5]

array([3, 1, 4, 2, 1], dtype=int64)

In [19]:
is_equal_to_3 = random_integers == 3

In [20]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [21]:
sum(is_equal_to_3)

31

In [22]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [23]:
id_counts.head()

dbf9fb14-2656    2
5f79f818-18af    2
297edb0f-3bb1    2
2a793ecf-05c6    2
6353fd55-d66e    2
Name: ID, dtype: int64

In [24]:
dupe_mask = id_counts == 2

In [25]:
dupe_mask[0:5]

dbf9fb14-2656    True
5f79f818-18af    True
297edb0f-3bb1    True
2a793ecf-05c6    True
6353fd55-d66e    True
Name: ID, dtype: bool

In [26]:
id_counts.index[0:5]

Index(['dbf9fb14-2656', '5f79f818-18af', '297edb0f-3bb1', '2a793ecf-05c6',
       '6353fd55-d66e'],
      dtype='object')

In [29]:
dupe_ids = id_counts.index[dupe_mask]

In [30]:
dupe_ids = list(dupe_ids)

In [31]:
len(dupe_ids)

313

In [32]:
dupe_ids[0:5]

['dbf9fb14-2656',
 '5f79f818-18af',
 '297edb0f-3bb1',
 '2a793ecf-05c6',
 '6353fd55-d66e']

In [34]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:]

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
5998   5f79f818-18af     200000    1          3         2   33     0      0   
6098   5f79f818-18af          0    0          0         0    0     0      0   
7869   dbf9fb14-2656     220000    2          3         1   47    -1     -1   
7969   dbf9fb14-2656          0    0          0         0    0     0      0   
17716  297edb0f-3bb1     120000    2          2         1   51    -1     -1   
17816  297edb0f-3bb1          0    0          0         0    0     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
5998       0      0  ...     119730     122537     109504      7100      5354   
6098       0      0  ...          0          0          0         0         0   
7869      -1     -1  ...      22792     184483      62140     50451     64775   
7969       0      0  ...          0          0          0         0         0   
17716      0      0  ...      58677      51549      46552     62462      2299   
17816      0      0  ...          0          0          0         0         0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
5998       4363      4816      4381      3330                           0  
6098          0         0         0         0                           0  
7869      22794    184483     62140     48080                           0  
7969          0         0         0         0                           0  
17716      1919      1838      2200     90000                           0  
17816         0         0         0         0                           0  

[6 rows x 25 columns]

In [35]:
df_zero_mask = df == 0

In [36]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)

In [37]:
sum(feature_zero_mask)

315

In [40]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()

In [41]:
df_clean_1.shape

(29685, 25)

In [42]:
df_clean_1['ID'].nunique()

29685

In [73]:
df_clean_1.to_csv(r"C:\Users\justt\AppData\Local\Temp\tmp5qm47__x", index=False)

In [75]:
df_clean_1 = pd.read_csv(r"C:\Users\justt\AppData\Local\Temp\tmp5qm47__x")

In [76]:
df_clean_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29685 entries, 0 to 29684
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   ID                          29685 non-null  object
 1   LIMIT_BAL                   29685 non-null  int64 
 2   SEX                         29685 non-null  int64 
 3   EDUCATION                   29685 non-null  int64 
 4   MARRIAGE                    29685 non-null  int64 
 5   AGE                         29685 non-null  int64 
 6   PAY_1                       29685 non-null  object
 7   PAY_2                       29685 non-null  int64 
 8   PAY_3                       29685 non-null  int64 
 9   PAY_4                       29685 non-null  int64 
 10  PAY_5                       29685 non-null  int64 
 11  PAY_6                       29685 non-null  int64 
 12  BILL_AMT1                   29685 non-null  int64 
 13  BILL_AMT2                   29685 non-null  in

In [77]:
df_clean_1['PAY_1'].head(5)

0     2
1    -1
2     0
3     0
4    -1
Name: PAY_1, dtype: object

In [78]:
df_clean_1['PAY_1'].value_counts()

0                13087
-1                5047
1                 3261
Not available     3021
-2                2476
2                 2378
3                  292
4                   63
5                   23
8                   17
6                   11
7                    9
Name: PAY_1, dtype: int64

In [79]:
valid_pay_1_mask = df_clean_1['PAY_1'] != 'Not available'

In [80]:
valid_pay_1_mask[0:5]

0    True
1    True
2    True
3    True
4    True
Name: PAY_1, dtype: bool

In [82]:
sum(valid_pay_1_mask)

26664

In [83]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask, :].copy()

In [84]:
df_clean_2.shape

(26664, 25)